vcs:
  type: git
agents:
  available:
  - opencode
  selection:
    preferred_implementer:
    preferred_reviewer:
project:
  uuid: bebf8d60-7c5d-4459-94b6-e0f3e4ad83f9
  slug: spec-kitty-events
  node_id: d036a097a835
